<a href="https://colab.research.google.com/github/PraveenBunker/45-days-of-python/blob/main/DAY14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df  = pd.read_json(url)

#by default false
df.sort_values("english")


# Descending order by english marks
df = df.sort_values("english", ascending=False)


# by default ascending method1
df.sort_values(by =["english"],ascending=[False])

#multiple column sort
# df.sort_values(by =["english","maths"],ascending=[False,True])


#data arrange in lower case
# df["name"] = df["name"].str.lower()
# df.sort_values("name")
# df


#add column
df["totel"] = df["english"] + df["maths"] + df["physics"]
df

#add row
df.loc[14] = ["praveen","male",50,80,80,210]
df

#delete column
df.drop("totel",axis=1)

#delete row

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23
14  praveen    male       50     80       80

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df = pd.read_json(url)

# Descending order by english marks
df = df.sort_values("english", ascending=False)
df

# print("\nascending order")

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df = pd.read_json(url)
# df.drop([7,8,9,10,11,12,13],inplace=True)
# df

df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05','2025-06-06']
df

ValueError: Length of values (6) does not match length of index (14)

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']
df['doj'].dtype

#convert to data

df['doj'] = pd.to_datetime(df['doj'])
df['doj'].dtype

# date operation
df['doj']= dt.year
df['doj']= dt.month
df['doj']= dt.day
# df['doj']= dt.day

NameError: name 'dt' is not defined

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)

df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']

# Convert to datetime
df['doj'] = pd.to_datetime(df['doj'])

# Date operations
df['year'] = df['doj'].dt.year
df['month'] = df['doj'].dt.month
df['day'] = df['doj'].dt.day
df['day'] = df['doj'].dt.day_name()

# 20 day
df['doj'] = pd.to_timedelta("20 days")


# df['dayofweek'] = df['doj'].dt.dayofweek
# df['dayofyear'] = df['doj'].dt.dayofyear
# df['quarter'] = df['doj'].dt.quarter

print(df)

       name  roll no  marks     doj  year  month        day
0   dheeraj      123     10 20 days  2025      1  Wednesday
1     kunal     1234     20 20 days  2025      2     Sunday
2  abhishek    12345     30 20 days  2025      3     Monday
3   praveen    12356     40 20 days  2025      4     Friday
4    anjali  1234567     50 20 days  2025      5     Monday