<a href="https://colab.research.google.com/github/PraveenBunker/45-days-of-python/blob/main/DAY12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## *Accessing a single DataFrame row by index*

You can access a single DataFrame row with the same methods as for Series: .loc for explicit indexing
and .iloc for implicit indexing. It returns a Series with an element for each column. As Index, it
contains the names of the columns.

In [ ]:
import pandas as pd
import numpy as np
price = pd . Series ([1.0 , 1.4 , 5] , index =[ 'a', 'b', 'c'])
quantity = pd . Series ([5 , 10 , 8] , index =[ 'a', 'b', 'c'])
liters = pd . Series ([1.5 , 0.3 , 1] , index =[ 'a', 'b', 'c'])
df = pd . DataFrame ({ 'Price ': price , 'Quantity ': quantity , 'Liters ': liters })
print ( df . loc ['a'])
print ( df . iloc [0])

Price        1.0
Quantity     5.0
Liters       1.5
Name: a, dtype: float64
Price        1.0
Quantity     5.0
Liters       1.5
Name: a, dtype: float64

In [ ]:
# import package pandas
import pandas as pd
l = [10,20,30]
df = pd.Series()
print(df)

0    10
1    20
2    30
dtype: int64

In [ ]:
d = {"name":"praveen","age":"20","city":"jaipur"}
df = pd.Series(data=d,index=["name","age","city"])
print(df)
# help(pd.Series)
# pd.series??

name    praveen
age          20
city     jaipur
dtype: object

Dataframe

In [ ]:
import pandas as pd
d= {
    "name":["kumal","praveen","dheeraj","anjali","yash"],
    "roll.no":[12,13,14,15,16],

}
df=pd.DataFrame(data=d,index=["a","b","c","d","e"])
print(df)

      name  roll.no
a    kumal       12
b  praveen       13
c  dheeraj       14
d   anjali       15
e     yash       16

In [18]:
# CSV Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2%20-%20Sheet1.csv"
df  = pd.read_csv(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [19]:
#Excel Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.xlsx"
df  = pd.read_excel(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [20]:
# JSON Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [21]:
# CSV Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2%20-%20Sheet1.csv"
df  = pd.read_csv(url)
print(df)
#head()

# df.head()
print(df.head())

#head 2 -> row data
print(df.head(2))

print(df.head(-2))

#tail()

# df.tail()
print(df.tail())

#tail 2 -> row data
print(df.tail(2))

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50
       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50
      name  roll no  marks
0  dheeraj      123     10
1    kunal     1234     20
       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50
      name  roll no  marks
3  praveen    12356     40
4   anjali  1234567     50

In [16]:
# JSON Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)

print(df.tail())
print(df.tail(2))
print(df.tail(-2))
#

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50
      name  roll no  marks
3  praveen    12356     40
4   anjali  1234567     50
       name  roll no  marks
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [26]:
# JSON Read file
# shape


import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)

print(df.shape)
#

(5, 3)

In [25]:
# JSON Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
df.info(4)
# print(df.info(4))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [35]:
# JSON Read file
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)

df["salary"] = [100,200,300,np.nan,500]
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
 3   salary   4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

       name  roll no  marks  salary
0   dheeraj      123     10   100.0
1     kunal     1234     20   200.0
2  abhishek    12345     30   300.0
3   praveen    12356     40     NaN
4    anjali  1234567     50   500.0

In [40]:
# rename
# JSON Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
df.rename(columns={"name":"student_name","marks":"salary"},inplace=True)
# original variable df -> value same
df

  student_name  roll no  salary
0      dheeraj      123      10
1        kunal     1234      20
2     abhishek    12345      30
3      praveen    12356      40
4       anjali  1234567      50

In [42]:
# JSON Read file
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
#describe
df.describe()

            roll no      marks
count  5.000000e+00   5.000000
mean   2.521250e+05  30.000000
std    5.492329e+05  15.811388
min    1.230000e+02  10.000000
25%    1.234000e+03  20.000000
50%    1.234500e+04  30.000000
75%    1.235600e+04  40.000000
max    1.234567e+06  50.000000

In [63]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
# df

# print(df)
# df.describe()
# df.info(4)
# print(df.shape)

# df.head()
# print(df.head())
# print(df.head(-2))

df.tail()
print(df.tail(3))

   Emp_ID  Name Department  Salary  Experience
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [69]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
# single column ka data get krne k liye
df["name"]
# add single column

df["salary"] = df["marks"] + 100
df
# add single column
df["salary12"] = [100,200,300,400,500]
df

       name  roll no  marks  salary  salary12
0   dheeraj      123     10     110       100
1     kunal     1234     20     120       200
2  abhishek    12345     30     130       300
3   praveen    12356     40     140       400
4    anjali  1234567     50     150       500

In [81]:
import pandas as pd
data = {
    "name": ["praveen","mayank","nirbhay"],
    "salary": [100,200,300]
}
df = pd.DataFrame(data)

# add column
# df["marks"]= [100,90,70]
df["marks"]= df["salary"]/2

# salary increment by 10 %
df["increment"]= df["salary"] + (df["salary"] / 10)

# column name change
df.rename(columns={"salary":"salary-increment"},inplace=True)
df

      name  salary-increment  marks  increment
0  praveen               100   50.0      110.0
1   mayank               200  100.0      220.0
2  nirbhay               300  150.0      330.0