<a href="https://colab.research.google.com/github/PraveenBunker/45-days-of-python/blob/main/DAY14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Reading JSON Data

2. Sorting Data (sort_values)

3. Sorting Multiple Columns

4. String Operations (str.lower)

5. Adding a Column

6. Adding a Row

7. Deleting a Column

8. Deleting a Row

9. Displaying DataFrame (df)

In [8]:
# ==============================
# Import Pandas Library
# ==============================
import pandas as pd

# ==============================
# Load JSON Data
# ==============================
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df = pd.read_json(url)

# ==============================
# Sort Data by English Marks
# ==============================

# Ascending Order (Default)
df.sort_values("english")

# Descending Order
df = df.sort_values("english", ascending=False)

# Descending Order (Method 2)
df.sort_values(by=["english"], ascending=[False])

# Multiple Column Sorting
# df.sort_values(by=["english", "maths"], ascending=[False, True])

# ==============================
# Sort String Data
# ==============================

# Convert Names to Lowercase
# df["name"] = df["name"].str.lower()

# Sort by Name
# df.sort_values("name")

# ==============================
# Add New Column
# ==============================

df["total"] = df["english"] + df["maths"] + df["physics"]

# ==============================
# Add New Row
# ==============================

df.loc[14] = ["praveen", "male", 50, 80, 80, 210]

# ==============================
# Delete Column
# ==============================

df.drop("total", axis=1)

# ==============================
# Delete Row
# ==============================

# Example:
# df.drop(14, axis=0)

# Display DataFrame
df

       name  gender  physics  maths  english  total
10    Gowri  Female      100    100      100    300
1    rajesh    Male       96    100       95    291
13  Jenifer  Female       67     88       90    245
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
0      arun    Male       88     87       78    253
12  Murugan    Male       34     89       78    201
2   moorthy    Male       89     90       70    249
7   Kavitha  Female       78     71       67    216
6    Sundar    Male       12     67       67    146
8    Dinesh    Male       56     45       67    168
11      Ram    Male       78     55       47    180
3      raja    Male       30     25       40     95
9      Hema  Female       71     90       23    184
14  praveen    male       50     80       80    210

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df = pd.read_json(url)

# Descending order by english marks
df = df.sort_values("english", ascending=False)
df

# print("\nascending order")

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

Rule: Column me jitni values assign karoge, DataFrame me utni hi rows honi chahiye.

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"

df = pd.read_json(url)

df.drop([6,7,8,9,10,11,12,13], inplace=True)

df['doj'] = [
    '2025-01-01',
    '2025-02-02',
    '2025-03-03',
    '2025-04-04',
    '2025-05-05',
    '2025-06-06'
]

# print(df)
df

      name  gender  physics  maths  english         doj
0     arun    Male       88     87       78  2025-01-01
1   rajesh    Male       96    100       95  2025-02-02
2  moorthy    Male       89     90       70  2025-03-03
3     raja    Male       30     25       40  2025-04-04
4     usha  Female       67     45       78  2025-05-05
5    priya  Female       56     46       78  2025-06-06

In [3]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']
df['doj'] = pd.to_datetime(df['doj'])
df
# # date operation
# df['doj']= dt.year
# df['doj']= dt.month
# df['doj']= dt.day
# df['doj']= dt.day

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)

df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']

# Convert to datetime
df['doj'] = pd.to_datetime(df['doj'])

# Date operations
df['year'] = df['doj'].dt.year
df['month'] = df['doj'].dt.month
df['day'] = df['doj'].dt.day
df['day'] = df['doj'].dt.day_name()

# 20 day
df['doj'] = pd.to_timedelta("20 days")


# df['dayofweek'] = df['doj'].dt.dayofweek
# df['dayofyear'] = df['doj'].dt.dayofyear
# df['quarter'] = df['doj'].dt.quarter

print(df)

       name  roll no  marks     doj  year  month        day
0   dheeraj      123     10 20 days  2025      1  Wednesday
1     kunal     1234     20 20 days  2025      2     Sunday
2  abhishek    12345     30 20 days  2025      3     Monday
3   praveen    12356     40 20 days  2025      4     Friday
4    anjali  1234567     50 20 days  2025      5     Monday